print("Dime las 3 notas de las calificaciones parciales")
califparc = int(input())
calif2parc = int(input())
calif3parc = int(input())
print("Dimela califación del examen final")
calif_final = int(input())
print("Dime la calificación del trabajo final")
trabajof = int(input())
print("Tu nota final es de", ((califparc+calif2parc+calif3parc)/3*0.55)+(calif_final*0.30)+(trabajof*0.15))